### ISSUE TITLE
Previously entered data is not retained/displayed

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#431] opened 2019-03-18 15:17 UTC
![image](https://user-images.githubusercontent.com/46028434/54540917-37ed3200-496f-11e9-9f0b-685b6ff83ca0.png)

**Comment by dutchTender** [comment] 2019-03-18 17:39
@l-stanny this is fixed after i removed those two lines.  
@nguyenvivi in the future, please also include specific steps of recreating this issue. this one is fine, but some time a screen shot does not tells me what was done to get to this point.

**Comment by dutchTender** [comment] 2019-03-18 17:40
@JackieBabos i think it is a good idea in the future, for some hard to understand issues, we should make a list and schedule a demo for the issue.

**Comment by nguyenvivi** [comment] 2019-03-18 18:08
@dutchTender - we will capture steps to help recreate the issue.

For this one in particular, we tried to complete the application supporting scenario 3, which is a foreign entity application.  When we got to the Review Page, the system informed us that we missed two required data fields in filing basis.  We selected "Return to application" to go back to the highlighted section.  Two issues occurred:

1. The system did not take us to filing basis/foreign registration section.
2. After provide the required information, we select "next", the system took us to the "additional information' page.  Note that we did answer all of the question in this section prior to select "Return to application" at the end of the process.  However, by selecting "next" from the filing basis page, the system took us back to the Additional Information page, and all of the data previously entered were removed.  This is the issue highlighted in #431.  

Please let us know if you want to have a quick call with us tomorrow to go over this issue with the internal BA team.

Thanks,
Vi

**Comment by dutchTender** [comment] 2019-03-18 19:31
@nguyenvivi  thanks vi, that was very helpful. i think this issue was an mistake by me when integrating front end java script code. there was some lines that was setting all check boxes and radio buttons to not checked on page load, which is not the behavior we wanted.

**Comment by dutchTender** [comment] 2019-03-20 14:14
@nguyenvivi we will leave this open. as the issue you are describing might be caused by another issue that was fixed in the last update. i was able to ran through your scenarios in the latest build with out any issues. but i might be missing a step. please test out this issue again when v.1.0.3 is deployed on thursday

**Comment by dutchTender** [comment] 2019-03-20 15:27
@nguyenvivi after looking into this issue more, this is a legitmate issue. we found that for concurrent use, after TTAB number field, there is no implementation after that. and no implementation for use in another form. those are the two components that needs to be build out

**Closed** 2019-04-02 18:16 UTC
Labels: Additional Information, Need Approval, Scenario High Priority, Version 1.0.4
